### PR TITLE
Copy tilesource instances to add styles

### PR DESCRIPTION
**Pull request by manthey**
Instead of reopening a tilesource when adding a style, copy the unstyled class and add the style information.

I've marked this as draft as I think it requires more tests to verify it does no harm.

### CODE REVIEW

**Comment by manthey** [comment]
@banesullivan This should speed up generating regions and tiles with different styles from the same source file by avoiding reopening the file handles.  I *think* it should work without issue, but, since file handles and locks are shared across classes, I think there is a potential that some additional lock may be needed in some case.

Please try it out and let me know if you see any issues when using multiple styles and sources.  I'll convert it to a non-draft when I've added more tests.

**Comment by banesullivan** [comment]
Thanks for pinging me on this. I'd like to stress test this with Django-large-image when I get back from PTO (tomorrow)

**Comment by manthey** [comment]
I've added some tests to ensure sources don't close handles prematurely.  @banesullivan If your testing is successful, I think we can merge this.

**Comment by banesullivan** [comment]
LGTM. Tests in `django-large-image` are happy, and my poking and prodding went well

**Review by banesullivan — APPROVED** [review]

**Pull request merged**
