### PR TITLE
Update tests to handle changes in job cancellation.

### PR DESCRIPTION
**Pull request by manthey**
Testing fails until this is fixed.  A number of other PRs have this change so that they can pass testing.

The `jobs.cancel` is event is consumed by the remote worker plugin, so we can't rely on it here.  Since we only use it in testing, it is easier to change the tests than to change the order that events are processed in Girder.

### CODE REVIEW

**Comment by zachmullen** [comment]
Change seems fine, but I'm wondering if the behavior of eating the event in the worker is correct?

**Comment by manthey** [comment]
This has to do with how Girder handles events.  If any process bound to an event calls `stopPropagation`, then the next handler won't get the event (of course).  Further, the test as I had originally written it was expecting the default event handler to fire, but remote worker now prevents the default and instead issues an update.

Since the test is just *preventing* the job from changing state, so that I can verify that certain conditions are handled properly, I am not concerned that remote worker changed what it was doing.

**Comment by cjh1** [comment]
The use of stopPropagation() also means that plugins essentially compete for the event, the plugin loaded first wins. I think this is a feature of the Girder event system.

**Comment by zachmullen** [comment]
Since it inspects the handler, I guess it does make sense for it to use stopPropagation.

**Pull request merged**
