### PR TITLE
Add support for OME Tiffs.

### PR DESCRIPTION
**Pull request by manthey**
This also adds generalized support for multi-frame large images.

### CODE REVIEW

**Comment by manthey** [comment]
This still needs tests.

**Comment by cooperlab** [comment]
Does this address the .scn format? I was surprised to see that OpenSlide claims to support this but we had issues reading these files.

**Comment by manthey** [comment]
No, this change probably won't directly help scn files.  The openslide reader can read *some* scn files, but not all.  There will be another PR to add better support for some of those files.

**Comment by manthey** [comment]
I've added python tests with a synthetic 3-frame OME tiff file I made.  The UI for choosing a frame doesn't have tests -- these are awkward to add in the current framework, so I'd prefer to defer adding those only to the girder-3 branch where it is easier.

If this works for others beside me, I'm content with the amount of testing for now.

**Pull request merged**
