### PR TITLE
restRequest path option was deprecated, so it has to change to url.

### PR DESCRIPTION
**Pull request by manthey**

### CODE REVIEW

**Comment by zachmullen** [comment]
I didn't realize `path` was deprecated, what's the rationale there? It was a girder restRequest-specific concept, why does it have to go away?

**Comment by manthey** [comment]
It was deprecated it in Girder PR #2273.  Perhaps @brianhelba or @jbeezley can explain why they both thought it a good idea.

**Comment by manthey** [comment]
With the deprecation and without this change, the javascript console is spammed with deprecation warnings (really, one would be enough).

**Comment by zachmullen** [comment]
I'm still not convinced the deprecation makes sense, has anyone come to its defense?

**Pull request merged**
