### PR TITLE
[WIP] Add a new tab widget for displaying metadata

### PR DESCRIPTION
**Pull request by jbeezley**
Following our discussion in the last meeting, this is a mock up for displaying multiple tabs in the metadata section.

screen shot 2016-08-19 at 9 24 42 am

### CODE REVIEW

**Comment by cdeepakroy** [comment]
The mockup looks great!

@manthey Can you please review this?

**Comment by manthey** [comment]
@cdeepakroy I was waiting until @jbeezley no longer had it marked as a WIP.

**Comment by jbeezley** [comment]
The changes here are fairly simple, I was hoping to a better idea about how the metadata was actually going to be stored in the items before moving on.  Also, I have some local changes that restores the ability to edit metadata, which this branch is missing.

**Comment by manthey** [comment]
Some of this was done in PR #457.  Anything else that is needed should be a new issue and PR.

**Pull request closed without merging**
