### PR TITLE
Support more geospatial files.

### LINKED ISSUE #676: Rasters with just GeoTransform are not handled
Geospatial rasters with no set projection or GCPs but with a GeoTransform are not able to be opened by GDALFileTileSource

Note: to mitigate this issue, I simply ran `gdal.Warp(..., ..., dstSRS='EPSG:4326')` on each raster

### PR DESCRIPTION
**Pull request by manthey**
There are files that have coordinates in lat/lon but no listed projection.

Closes #676.

### CODE REVIEW

**Comment by banesullivan** [comment]
This still isn't working for the specific data that I have

**Comment by banesullivan** [comment]
I'm seeing segfaults....

```py
(large_image_dev) ➜  large_image git:(more-geospatial) python
Python 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 01:59:00)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import large_image
>>> large_image.__file__
'/Users/bane/Software/kw/large_image/large_image/__init__.py'
>>> large_image.open('/Users/bane/Software/OASIS/data/og_Data_scripts_Sept2021/PRISM_PPT/2017/PRISM_PPT_20170714.tif')
Created LRU Cache for 'tilesource' with 81 maximum size
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
[1]    7133 segmentation fault  python
```

**Comment by manthey** [comment]
> This still isn't working for the specific data that I have

It works for the sample file you shared privately.  There is a structurally similar file here: https://data.kitware.com/api/v1/file/61969eb32fa25629b9f3638b/download

**Comment by banesullivan** [comment]
I'm getting segfaults for that file as well so something is probably wrong with my local installation. I'll investigate this soon here

**Comment by manthey** [comment]
> I'm seeing segfaults....
> 
> ```python
> (large_image_dev) ➜  large_image git:(more-geospatial) python
> Python 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 01:59:00)
> [Clang 11.1.0 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import large_image
> >>> large_image.__file__
> '/Users/bane/Software/kw/large_image/large_image/__init__.py'
> >>> large_image.open('/Users/bane/Software/OASIS/data/og_Data_scripts_Sept2021/PRISM_PPT/2017/PRISM_PPT_20170714.tif')
> Created LRU Cache for 'tilesource' with 81 maximum size
> TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
> [1]    7133 segmentation fault  python
> ```

Based on that segfault, it isn't trying to parse it as geospatial -- it is using some other tile source.  What do you see with something like
```
import large_image

print(large_image.tilesource.isGeospatial(<path>))
```

**Comment by banesullivan** [comment]
Same segfault

```py
>>> import large_image
>>> p = '/Users/bane/Software/OASIS/data/og_Data_scripts_Sept2021/PRISM_PPT/2017/PRISM_PPT_20170714.tif'
>>> large_image.tilesource.isGeospatial(p)
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
[1]    13148 segmentation fault  python
```

**Comment by manthey** [comment]
> Same segfault
> 
> ```python
> >>> import large_image
> >>> p = '/Users/bane/Software/OASIS/data/og_Data_scripts_Sept2021/PRISM_PPT/2017/PRISM_PPT_20170714.tif'
> >>> large_image.tilesource.isGeospatial(p)
> TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
> [1]    13148 segmentation fault  python
> ```

Odd -- what version of the GDAL wheel do you have installed?

**Comment by banesullivan** [comment]
I was on 3.3.2 and so I reinstalled to 3.4.0 it's working now... 🤷🏻‍♂️

**Review by banesullivan — APPROVED** [review]

**Comment by manthey** [comment]
> I was on 3.3.2 and so I reinstalled to 3.4.0 it's working now... 🤷🏻‍♂️

Were you importing any other libraries before large_image (this may or may not be germane, since the problem might occur even without such an import)?  There was a curious issue with importing torch before gdal, which turned out that one of libraries that we were building for GDAL happened to use -ftls-model=initial-exec which exhausted some local resource for static thread local storage which caused a failed import.  In other bug reports on this topic it causes segfaults.

**Comment by banesullivan** [comment]
> Were you importing any other libraries before large_image

Nope, just large_image. I think I had a mismatch of versions between my python gdal bindings and the gdal binaries (on Mac so I can't use the large_image_wheels)

**Pull request merged**
