### PR TITLE
add annotation badge to large image preview

### PR DESCRIPTION
**Pull request by sgratzl**
image

### CODE REVIEW

**Comment by manthey** [comment]
One minor issue:

You can optionally change the large_image plugin settings to show label and macro images.  The badge  currently appears on all images; it should just be shown on one of them (just the thumbnail, I think).

image

**Comment by sgratzl** [comment]
please try again

**Comment by manthey** [comment]
Great.

The linter is complaining about two extra lines (see the output of the circle build).

**Comment by manthey** [comment]
@sgratzl If you didn't see it, circle now shows a linting error in the styl file.

**Pull request merged**
