### PR TITLE
Acquire lock when accessing GDAL dataset

### PR DESCRIPTION
**Pull request by wphicks**
Backport changes from the Girder 3 branch to provide thread safety for GDAL datasets in the Mapnik tilesource

### CODE REVIEW

**Comment by aashish24** [comment]
@wphicks so we had this code and it got removed, is that correct.

**Comment by wphicks** [comment]
@aashish24 I'm sorry, I'm not sure I understand the question. This is a backport of changes on the girder-3 branch.

It looks like CI failed because of server segfaults. I'm stumped as to why adding those locks would cause segfaults; I was actually hoping it would take care of the segfaults we've been seeing in our deployments. If anyone has any insight on this or has seen similar behavior, I'm very much open to ideas.

**Comment by manthey** [comment]
The travis CI for Python 2 uses an ancient version of GDAL (1.10).  I wonder if recent changes to other packages are now breaking with this.  I'm hunting for the issue...

**Comment by manthey** [comment]
large_image master is failing in the same way, so the CI issues are not related to this PR.  There is a fix for CI in #359.  Once that is merged to master, this can be based off it and should pass.

**Comment by manthey** [comment]
@wphicks Can you merge or rebase on master.  That should allow the CI to pass.

**Comment by wphicks** [comment]
Just performed the rebase; thanks for following up on this @manthey

**Comment by manthey** [comment]
I'm not sure why the circle tests aren't running.  I'll override the requirement this time and merge it.

**Pull request merged**
